Repository ad-ha/ide_api, pull requests merged in 2022-01, with the labels that each got.

#9 Update reading class
  custom_components/ide_api/ide_api.py
  custom_components/ide_api/sensor.py
Labels: enhancement, fix

#8 Change target reading
  custom_components/ide_api/sensor.py
Labels: enhancement, fix

#12 Rename custom_components/ide_api/hacs.json to hacs.json
  hacs.json
Labels: documentation

#22 Entity xx implements device_state_attributes
  custom_components/ide/sensor.py
Labels: good first issue, fix

#16 Import oligo as a dependency
  .gitignore
  custom_components/ide/__init__.py
  custom_components/ide/ide_api.py
  custom_components/ide/manifest.json
  custom_components/ide/sensor.py
  docker-compose.yml
Labels: enhancement
